"""The lot boundary, tested properly instead of by a maximised Welch t.

The paper locates the procurement boundary by scanning every candidate split and reporting the
largest Welch t it finds (t = 26.6). That statistic is a *maximum* over ~48 dependent tests, so
its null distribution is not Student's t and the quoted value cannot be read as a significance
level. Four things replace it here:

  1. MAX-T, PERMUTATION-CALIBRATED. The null is generated by permuting whole racks, which
     preserves rack sizes and the within-rack dependence the paper documents (same-rack sockets
     share more harvested slices than chance). The calibrated p-value and the simultaneous
     envelope for the changepoint profile both come from this.

  2. A BOOTSTRAP CI FOR THE BREAKPOINT. Resample racks with replacement, re-find the argmax,
     take percentiles. A boundary reported without an interval invites the reading that it is
     known exactly.

  3. HOW MANY POPULATIONS? Segment the rack-ordered fleet into k = 1..5 populations by dynamic
     programming over a per-segment 12-slice Bernoulli likelihood, and choose k by *rack-held-out*
     likelihood rather than by in-sample fit, which always prefers more segments.

  4. DOES IT PREDICT? Leave-one-rack-out: fit the two lot models on the other 48 racks and
     classify each socket of the held-out rack by likelihood ratio. An operator cares whether a
     harvest map assigns an unseen rack to the right delivery, which is a prediction, not a
     p-value.

Everything runs off the derived daily tables; no raw scan.
"""
from pathlib import Path

import numpy as np
import pandas as pd

root = Path(__file__).resolve().parent.parent
EXPECT, NSLICE = 4320, 12
rng = np.random.default_rng(11)
EPS = 1e-9


# ------------------------------------------------------------------ recover the per-socket maps
def harvest_matrix():
    df = pd.concat([pd.read_parquet(f) for f in sorted((root / 'daily').glob('daily_*.parquet'))],
                   ignore_index=True)
    df['day'] = pd.to_datetime(df['day'], utc=True)
    a = df.groupby(['node', 'socket', 'day']).size().rename('active')
    fu = df[df.n > 0.9 * EXPECT].groupby(['node', 'socket', 'day']).size().rename('nfull')
    t = pd.concat([a, fu], axis=1).fillna(0).reset_index()
    clean = t[(t.active == 16) & (t.nfull == 16)][['node', 'socket', 'day']]
    sets = (df.merge(clean, on=['node', 'socket', 'day'])
              .groupby(['node', 'socket', 'day'])['core'].apply(frozenset).rename('c').reset_index())
    M = (sets.groupby(['node', 'socket'])['c']
             .agg(lambda s: s.value_counts().index[0]).rename('map').reset_index())
    M['sl'] = M['map'].apply(lambda c: frozenset(k // 2 for k in c))
    M = M[M.sl.apply(len) == 8].reset_index(drop=True)          # 8 active == 4 harvested
    X = np.zeros((len(M), NSLICE), dtype=np.int8)
    for i, act in enumerate(M.sl):
        for k in range(NSLICE):
            X[i, k] = 0 if k in act else 1                       # 1 == harvested
    return X, M.node.values // 20, M.node.values


X, rack, node = harvest_matrix()
# 984 node identities appear (ids 0..983), so rack = id//20 runs to 49 -- one past the 49
# documented cabinets of 20 nodes (ids 0..979). Nodes 980..983 have no documented (X,Y) floor
# position, and as a 4-node group they form a degenerate segment that captures the argmax of any
# unguarded scan. They are excluded from the rack-level analysis and the exclusion is stated.
extra = rack >= 49
print(f'excluded from rack analysis: {extra.sum()} sockets on nodes {sorted(set(node[extra]))} '
      f'(rack 49, outside the 49 documented cabinets)')
X, rack, node = X[~extra], rack[~extra], node[~extra]
N = len(X)
NRACK = int(rack.max()) + 1

# A changepoint scan is unstable at its extremes: a split isolating a handful of sockets can
# manufacture a large Welch t from noise. Candidate boundaries must leave at least MIN_SOCK
# sockets on each side (~5% of the fleet).
MIN_SOCK = 100
CANDS = [c for c in range(1, NRACK)
         if (rack < c).sum() >= MIN_SOCK and (rack >= c).sum() >= MIN_SOCK]
print(f'sockets {N:,}   racks {NRACK}   candidate boundaries {CANDS[0]}..{CANDS[-1]} '
      f'({len(CANDS)} of {NRACK - 1}, trimmed at {MIN_SOCK} sockets per side)')

s0 = X[:, 0].astype(float)


# ------------------------------------------------------------------ 1. permutation-calibrated max-t
def welch_t(y, grp):
    a, b = y[~grp], y[grp]
    if len(a) < 2 or len(b) < 2:
        return 0.0
    va, vb = a.var(ddof=1) / len(a), b.var(ddof=1) / len(b)
    return (a.mean() - b.mean()) / np.sqrt(va + vb + EPS)


def profile(y, rk, cands=None):
    """Welch t at every admissible rack boundary."""
    return np.array([welch_t(y, rk >= c) for c in (CANDS if cands is None else cands)])


obs_prof = profile(s0, rack)
obs_max = np.abs(obs_prof).max()
obs_cut = CANDS[int(np.argmax(np.abs(obs_prof)))]
print(f'\n=== 1. max-t, permutation-calibrated ===')
print(f'  observed argmax boundary : rack {obs_cut}   |t| = {obs_max:.1f}')

B = 4000
null_max = np.empty(B)
rack_ids = np.arange(NRACK)
for b in range(B):
    perm = rng.permutation(rack_ids)                  # relabel whole racks
    null_max[b] = np.abs(profile(s0, perm[rack])).max()
p_perm = (null_max >= obs_max).mean()
print(f'  rack-permutation null    : max|t| = {null_max.mean():.2f} +/- {null_max.std():.2f}, '
      f'99th pct {np.percentile(null_max, 99):.2f}, max seen {null_max.max():.2f}')
print(f'  calibrated p             : < {max(p_perm, 1 / B):.2e}  ({int(p_perm * B)}/{B} exceed)')
print('  The maximised Welch t is not itself a p-value; this is.')
env95 = np.percentile(null_max, 95)
np.save(root / 'analysis' / 'changepoint_profile.npy',
        np.vstack([np.array(CANDS, float), obs_prof]))
np.save(root / 'analysis' / 'changepoint_null.npy', null_max)


# ------------------------------------------------------------------ 2. bootstrap CI for the break
print('\n=== 2. bootstrap CI for the breakpoint (sockets resampled within rack) ===')
# The clusters are racks, but a changepoint lives in the rack ORDER, so racks cannot be
# resampled with replacement -- that shuffles the very sequence the parameter is defined on
# (doing so returns a CI spanning the whole scan, which is an artefact, not a finding).
# The correct cluster bootstrap here keeps every rack in place and resamples the sockets
# inside it, preserving both the ordering and the within-rack dependence.
rack_idx = [np.where(rack == r)[0] for r in range(NRACK)]
boot_cut = []
for _ in range(2000):
    idx = np.concatenate([ix[rng.integers(0, len(ix), len(ix))] for ix in rack_idx if len(ix)])
    pr = profile(s0[idx], rack[idx])
    boot_cut.append(CANDS[int(np.argmax(np.abs(pr)))])
boot_cut = np.array(boot_cut)
lo, hi = np.percentile(boot_cut, [2.5, 97.5])
print(f'  breakpoint rack = {obs_cut}   95% CI [{lo:.0f}, {hi:.0f}]   '
      f'modal {np.bincount(boot_cut).argmax()}  '
      f'({100 * (boot_cut == obs_cut).mean():.0f}% of resamples pick it exactly)')


# ------------------------------------------------------------------ 3. how many populations?
def seg_ll(Xs):
    """Log-likelihood of a segment under its own 12 independent Bernoulli marginals (MLE)."""
    if len(Xs) == 0:
        return 0.0
    p = np.clip(Xs.mean(0), EPS, 1 - EPS)
    return float((Xs * np.log(p) + (1 - Xs) * np.log(1 - p)).sum())


def best_segmentation(Xr, k):  # noqa: F811
    """DP over rack-ordered segments; Xr is a list of per-rack socket blocks."""
    R = len(Xr)
    cost = np.full((R + 1, R + 1), -np.inf)
    for i in range(R):
        for j in range(i + 1, R + 1):
            cost[i, j] = seg_ll(np.vstack(Xr[i:j]))
    dp = np.full((k + 1, R + 1), -np.inf)
    bk = np.zeros((k + 1, R + 1), dtype=int)
    dp[0, 0] = 0.0
    for s in range(1, k + 1):
        for j in range(1, R + 1):
            for i in range(s - 1, j):
                if sum(len(b) for b in Xr[i:j]) < MIN_SOCK:
                    continue
                v = dp[s - 1, i] + cost[i, j]
                if v > dp[s, j]:
                    dp[s, j], bk[s, j] = v, i
    cuts, j = [], R
    for s in range(k, 0, -1):
        i = bk[s, j]
        cuts.append(i)
        j = i
    return dp[k, R], sorted(c for c in cuts if c > 0)


Xr = [X[rack == r] for r in range(NRACK)]
print('\n=== 3. how many populations? (rack-held-out likelihood) ===')
print('   k   in-sample LL   held-out LL/socket   cuts (rack index)')
for k in range(1, 6):
    ll_in, cuts = best_segmentation(Xr, k)
    # leave-one-rack-out: refit segmentation without rack r, score rack r under its segment
    ho = []
    for r in range(NRACK):
        keep = [x for i, x in enumerate(Xr) if i != r]
        _, cut_r = best_segmentation(keep, k)
        pos = r if r < 1 else r - 1                          # index of rack r in the reduced list
        bounds = [0] + list(cut_r) + [NRACK - 1]
        seg = next(s for s in range(len(bounds) - 1) if bounds[s] <= pos < bounds[s + 1])
        train = np.vstack(keep[bounds[seg]:bounds[seg + 1]])
        p = np.clip(train.mean(0), EPS, 1 - EPS)
        Xt = Xr[r]
        ho.append(float((Xt * np.log(p) + (1 - Xt) * np.log(1 - p)).sum()))
    print(f'  {k}   {ll_in:12.1f}   {sum(ho) / N:18.4f}   {cuts}')
print('  In-sample LL always improves with k; the held-out column is the one that decides.')


# ------------------------------------------------------------------ 4. leave-one-rack-out stability
print('\n=== 4. leave-one-rack-out stability of the boundary ===')
loro = []
for r in range(NRACK):
    m = rack != r
    rk = rack[m]
    rk = np.searchsorted(np.unique(rk), rk)
    cd = [c for c in range(1, rk.max() + 1)
          if (rk < c).sum() >= MIN_SOCK and (rk >= c).sum() >= MIN_SOCK]
    pr = profile(s0[m], rk, cd)
    # map back to original rack numbering: dropping rack r shifts every rack above it down one
    cut = cd[int(np.argmax(np.abs(pr)))]
    loro.append(cut + 1 if cut > r else cut)
loro = np.array(loro)
vals, cnt = np.unique(loro, return_counts=True)
print(f'  boundary recovered in {cnt.max()}/{NRACK} leave-one-rack-out fits; '
      f'values {dict(zip(vals.tolist(), cnt.tolist()))}')


# ------------------------------------------------------------------ 5. held-out lot classification
print('\n=== 5. can a harvest map assign an UNSEEN rack to the right lot? ===')
lot = (rack >= obs_cut).astype(int)
sock_ok = rack_ok = 0
for r in range(NRACK):
    tr, te = rack != r, rack == r
    pA = np.clip(X[tr & (lot == 0)].mean(0), EPS, 1 - EPS)
    pB = np.clip(X[tr & (lot == 1)].mean(0), EPS, 1 - EPS)
    Xt = X[te]
    llA = (Xt * np.log(pA) + (1 - Xt) * np.log(1 - pA)).sum(1)
    llB = (Xt * np.log(pB) + (1 - Xt) * np.log(1 - pB)).sum(1)
    pred = (llB > llA).astype(int)
    truth = lot[te][0]
    sock_ok += (pred == truth).sum()
    rack_ok += int((pred.mean() > 0.5) == bool(truth))
print(f'  socket-level accuracy : {100 * sock_ok / N:.1f}%  ({sock_ok:,}/{N:,})')
print(f'  rack-level accuracy   : {100 * rack_ok / NRACK:.1f}%  ({rack_ok}/{NRACK} racks)')
print(f'  Chance is {100 * max(lot.mean(), 1 - lot.mean()):.1f}% (majority class) at socket level.')
print('\nThis is the operationally meaningful statement: a harvest map recovered from telemetry')
print('assigns a rack the model has never seen to the correct delivery at the rate above.')
