"""Fig. 5, rebuilt from the 1,948-socket census instead of the stale 240-socket run.

The shipped figure was generated by `make_fig_thermal_v2.py`, whose title reads "240 sockets"
and whose markers plot +0.377 / +0.3075 -- the subsample values. The surrounding section has
since become a fleet-wide census reporting +0.372 / +0.312, so the figure contradicted its own
text on the paper's single most important contrast.

This rebuilds the decay curve from `thermal_corr_allnodes.npy`, the pooled census matrix. One
honest difference from the old figure: the band here is the spread ACROSS CORE PAIRS at a given
index distance, not a bootstrap over sockets, because the per-pair samples behind the census were
not retained. It is labelled as such. The two headline markers carry the socket-level CIs already
reported in the text.
"""
import os
import tempfile
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use('Agg')
import matplotlib.pyplot as plt   # noqa: E402

root = Path(__file__).resolve().parent
FIG = root.parent / 'paper' / 'figures'
SCRATCH = Path(os.environ.get('FIGURE_PREVIEW_DIR', tempfile.gettempdir()))
BLUE, ORANGE, GREEN = '#2b6cb0', '#dd6b20', '#2f855a'
GREY, INK = '#a0aec0', '#2d3748'
plt.rcParams.update({'font.size': 8, 'axes.grid': True, 'grid.alpha': .25,
                     'grid.linewidth': .5, 'figure.dpi': 200, 'savefig.bbox': 'tight',
                     'axes.edgecolor': '#cbd5e0', 'axes.labelcolor': INK,
                     'text.color': INK, 'xtick.color': INK, 'ytick.color': INK,
                     'axes.spines.top': False, 'axes.spines.right': False})

C = np.load(root / 'thermal_corr_allnodes.npy')
NC = C.shape[0]

gaps, means, los, his = [], [], [], []
for d in range(1, NC):
    v = np.array([C[i, j] for i in range(NC) for j in range(NC) if j - i == d])
    if not len(v):
        continue
    gaps.append(d)
    means.append(v.mean())
    los.append(np.percentile(v, 25))
    his.append(np.percentile(v, 75))
gaps = np.array(gaps)

# distance-1 pairs split by whether they share a slice
within = np.array([C[2 * k, 2 * k + 1] for k in range(NC // 2)])
cross = np.array([C[2 * k + 1, 2 * k + 2] for k in range(NC // 2 - 1)])

fig, ax = plt.subplots(figsize=(3.4, 2.3))
ax.fill_between(gaps, los, his, color=BLUE, alpha=.18, lw=0,
                label='interquartile range across core pairs')
ax.plot(gaps, means, 'o-', color=BLUE, ms=3.2, lw=1.3, label='pooled mean')
ax.axhline(0, color=INK, lw=.7)

# the two headline values, with the socket-level CIs reported in Sec. IV-E
ax.errorbar([1], [0.372], yerr=[[0.372 - 0.369], [0.376 - 0.372]], fmt='v', color=ORANGE,
            ms=7, capsize=2.5, lw=1.4, zorder=5, markeredgecolor='white', markeredgewidth=.8,
            label='within-slice siblings  $r=+0.372$')
ax.errorbar([1], [0.312], yerr=[[0.312 - 0.306], [0.317 - 0.312]], fmt='^', color=GREEN,
            ms=7, capsize=2.5, lw=1.4, zorder=5, markeredgecolor='white', markeredgewidth=.8,
            label='cross-slice neighbours $r=+0.312$')
ax.set_xlabel('core index distance $|i-j|$')
ax.set_ylabel('residual correlation $r$')
ax.set_xticks(range(0, NC, 4))
ax.legend(fontsize=5.8, frameon=False, loc='upper right')
ax.set_title('1,948 sockets, both p0 and p1, full month 2022-08, native 20 s cadence',
             fontsize=6.8, color=INK)
fig.savefig(FIG / 'f4_thermal_decay.pdf')
fig.savefig(SCRATCH / 'f4.png', dpi=150)
plt.close(fig)
print('wrote f4_thermal_decay.pdf from the census matrix')
print(f'  within-slice mean over pooled matrix : {within.mean():+.4f}')
print(f'  cross-slice  mean over pooled matrix : {cross.mean():+.4f}')
print(f'  contrast                             : {within.mean() - cross.mean():+.4f}')
